---
  - name: Install Apache
    yum: 
      name: httpd 
      state: latest
    tags: httpd

  - name: Assign Permissions to httpd directory
    become: true
    become_user: root
    become_method: sudo
    file: 
      path: /var/www/html
      mode: 0777
      owner: apache
      group: apache

  - name: Copy Hello HTML
    
  - name: Start Apache
    become: true
    become_user: root
    become_method: sudo
    shell: /usr/bin/systemctl start httpd.service
    tags: start apache

  - name: Enable Apache Service
    become: true
    become_user: root
    become_method: sudo
    shell: /usr/bin/systemctl enable httpd.service
    tags: enable apache