---
 
- name: Start & Enable Web Server
  become: true
  become_user: root
  become_method: sudo
  include: apache-start.yml

- name: SSL Creation
  become: true
  become_user: root
  become_method: sudo
  include: ssl-create.yml

- name: SSL Configuration
  become: true
  become_user: root
  become_method: sudo
  include: ssl-task.yml