---

- name: Configure the Apache Web Server
  become: true
  become_user: root
  become_method: sudo
  include: envSetup.yml
 
- name: Start & Enable Web Server
  become: true
  become_user: root
  become_method: sudo
  include: apache-start.yml

- name: SSL Configuration
  become: true
  become_user: root
  become_method: sudo
  include: ssl-task.yml