---
 
  #- name: Start & Enable Web Server
  #  host: webservers
  #  include: apache-start.yml

  - name: SSL Creation
    become: true
    become_user: root
    become_method: sudo
    include: ssl-create.yml

  - name: SSL Configuration
    become: true
    become_user: root
    become_method: sudo
    include: ssl-task.yml