---

  - name: Create the SSL Directory Structure
    file:
      path: /etc/httpd/sites/ssl/
      state: directory
      mode: 0755
      owner: apache
      group: apache

  - name: Install Open SSL Dependencies
    easy_install:
      name: pip
      state: latest

  - name: Install Open SSL Dependencies
    pip:
      name: ['boto3', 'awscli','pyopenssl']
      state: latest

 # - name: make sure SSL certificate is existing and secured
 #   file:
 #     state:  file
 #     path:   '{{ item.path }}'
 #     owner:  root
 #     group:  root
 #     mode:   '{{ item.mode }}'
 #   with_items:
 #     - path: /etc/pki/tls/certs/localhost.crt
 #       mode: '0644'
 #     - path: /etc/pki/tls/certs/localhost.csr
 #       mode: '0600'
 #     - path: /etc/pki/tls/cert.pem
 #       mode: '0600'

  - name: Install SSL certificate
    copy:
      src: apachessl.crt
      dest: /etc/httpd/sites/ssl/apachectl.crt
      owner: apache
      group: apache
      mode: 0644
  
  - name: make sure SSL private key is installed
    copy:
      src: apachessl.key
      dest: /etc/httpd/sites/ssl/
      owner: apache
      group: apache
      mode: 0600
    no_log: true

  - name: make sure SSL pem is installed
    copy:
      src: apachessl.pem
      dest: /etc/httpd/sites/ssl/
      owner: apache
      group: apache
      mode: 0600
    no_log: true