---
  - name: Makr Dir for Hello HTML
    file:
      path: /var/www/html/hello
      state: directory
      mode: 0755
      owner: apache
      group: apache
    
  #- name: enabled mod_rewrite
  #  apache2_module: 
  #      name: rewrite 
  #      state: present
  #  notify:
  #    - restart httpd

  - name: Copy Index.html
    template: 
      src: index.html 
      dest: /var/www/html/hello/
      owner: apache
      group: apache
      mode: 0755

  - name: Copy Conf File
    template: 
      src: httpd.conf
      dest: /etc/httpd/conf/
      owner: apache
      group: apache
      mode: 0755
    notify:
      - restart httpd

  - name: Check for 443
    debug:
      msg: "Check URL {{ inventory_hostname }}"

  - name: Restart HTTPD
    become: true
    become_user: apache
    become_method: sudo
    shell: /usr/bin/systemctl restart httpd.service

 # - name: apache2 virtualhost on port 443
 #   copy: 
 #    file: 000-default.conf
 #    dest: /etc/httpd/conf.modules.d/000-default.conf
 #   notify:
 #     - restart apache2

 # - name: create virtual host file
 #   template: 
 #     src: virtualhost.conf 
 #     dest: /etc/httpd/conf.modules.d/00-default.conf
 #     state: present

  - name: restart httpd
    service:
      name: httpd
      state: restarted