---
- hosts: webservers
  gather_facts: true
  remote_user: ec2-user

  tasks:
      - name: Create an EC2 key
        ec2_key:
          name: "Ubuntu-Ansible"
          region: "us-east-1"
        register: ec2_key

      - name: Save private key
        copy: 
          content: "{{ ec2_key }}"
          dest: "/Web-App-Deploy/inventory/Ubuntu-Ansible.pem"
          mode: 0600
        when: ec2_key.changed

      - name: Provision an EC2 Instance
        ec2:
            key_name: Ubuntu-Ansible
            instance_type: t2.micro
            region: us-east-1
            image: ami-011b3ccf1bd6db744
            wait: true
            exact_count: 1
            count_tag: env
            instance_tags:
              Name: Demo-4
        register: ec2

      - name: Add the newly created EC2 instance(s) to host group
        lineinfile: 
          dest: "{{ hostpath }}"
          regexp: "{{ item.public_ip }}"
          insertafter: "[webserver]" 
          line: "{{ item.public_ip }} {{hoststring}}"
          state: present
        with_items: "{{ ec2.instances }}"

      - name: Add public keys for Users
        authorized_key: 
              user: "{{ app_code_user }}"
              key: "{{ lookup('file', item) }}"
        with_fileglob:
            - ./public_keys/*.pub

      - name: Wait for SSH to come up
        local_action: wait_for 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
        with_items: "{{ ec2.instances }}"