---

  - name: Create an EC2 key
    ec2_key:
      name: "Ubuntu-Ansible"
      region: "us-east-1"
    register: ec2_key

  - name: Save private key
    copy: 
      content: "{{ ec2_key }}"
      dest: "/Web-App-Deploy/inventory/Ubuntu-Ansible.pem"
      mode: 0600
    when: ec2_key.changed