---

  - name: Provision an EC2 Instance
    ec2:
        key_name: Ubuntu-Ansible
        instance_type: t2.micro
        region: us-east-1
        image: ami-011b3ccf1bd6db744
        wait: true
        exact_count: 1
        count_tag: env
        instance_tags:
          Name: Demo-4
    register: ec2
