---

  - name: Add the newly created EC2 instance(s) to host group
    lineinfile: 
      dest: "{{ hostpath }}"
      regexp: "{{ item.public_ip }}"
      insertafter: "[webserver]" 
      line: "{{ item.public_ip }}"
      state: present
    with_items: "{{ ec2.instances }}"

  - name: Add public keys for Users
    authorized_key: 
          user: "{{ app_code_user }}"
          key: "{{ lookup('file', item) }}"
    with_fileglob:
        - ./public_keys/*.pub

  - name: Wait for SSH to come up
    local_action: wait_for 
                  host={{ item.public_ip }} 
                  port=22 
                  state=started
    with_items: "{{ ec2.instances }}"